### ISSUE TITLE
有道一键网页翻译 /youdao_translate 似乎在大多数网站都无法使用

### ISSUE THREAD

**Issue by vwhy** [h2y/link-fix#14]
例如：google.com github.com stackoverflow.com wikipedia.org
在 greasyfork.org 上倒是可以用。

**Comment by h2y** [comment]
因为这些网站设置了禁止其他域脚本的写入，所以浏览器不能执行。这个暂时没啥解决办法。

**Comment by vwhy** [comment]
> 因为这些网站设置了禁止其他域脚本的写入，所以浏览器不能执行。这个暂时没啥解决办法。

原来如此
