### ISSUE TITLE
自动京东配送脚本总是在搜索关键字后增加“自营”二字

### ISSUE THREAD

**Issue by wellkens** [h2y/link-fix#20]
自动京东配送脚本总是在搜索关键字后增加“自营”二字，每次搜索都要删除这两个字……

**Comment by h2y** [comment]
因为目前只有这样，才能得到京东自营的结果

**Comment by wellkens** [comment]
我就是忘了之前搜索什么了，那个搜索之后没有自营两个字和加上自营两个字差别是有的，而且不加自营两个字结果更准确，而且目前的情况来说，能选上京东物流基本上差不多了
PS：之前收到提示消息但是一直没找到这个话题……
