### ISSUE TITLE
有道一键网页翻译脚本无法执行

### ISSUE THREAD

**Issue by vohv** [h2y/link-fix#22]
![image](https://user-images.githubusercontent.com/28553596/66312500-5f274300-e943-11e9-9682-5797947ee04a.png)

**Comment by h2y** [comment]
请使在网页中点击右键，主动运行此脚本

**Comment by frezoow** [comment]
> 
> 
> 请使在网页中点击右键，主动运行此脚本

目前在chrome可用在右键菜单找到开关，firefox70.1是没有的，能适配一下么？
---
另外，新手翻译为什么页面全都是英文，是不是有些问题？
