### ISSUE TITLE
有关【自动勾选京东配送】功能，能否做到将商品列表内的【京东配送】过滤掉？

### ISSUE THREAD

**Issue by HoneyLuka** [h2y/link-fix#8]
不太了解这块，所以不知道能否在数据上区分【自营】和【京东配送】，现在只有自营的才是真正自营的，京东配送的依然有可能是第三方，并且官方页面上没有方法可以将京东配送过滤掉。

<img width="464" alt="wx20171229-165104 2x" src="https://user-images.githubusercontent.com/4635725/34433192-97345654-ecb8-11e7-83c1-b4c4848367a7.png">

**Comment by h2y** [comment]
貌似需要在搜索时添加「自营」关键字。
谢谢反馈

**Comment by h2y** [comment]
已完成
